name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install
      working-directory: Client

    - name: Run build
      run: npm run build
      working-directory: Client

    - name: Run tests (allow no tests)
      run: npm test -- --passWithNoTests
      working-directory: Client

